shared_preload_libraries = 'pg_stat_statements'
track_io_timing = on
timezone = 'Europe/Brussels'
log_timezone = 'Europe/Brussels'
# log_statement = all
# log_line_prefix = '%t %h %u [%d] '
max_connections = 512
max_worker_processes = 16
max_parallel_workers = 16
max_parallel_workers_per_gather = 8
temp_file_limit = 8GB

# small index b tree scan

random_page_cost = 1.1

# big sequential table scan

seq_page_cost = 1.0

# generate many concurrent disk requests, taking advantage of fast NVMe hardware.

effective_io_concurrency = 200

# Up to 80GB of RAM is available for caching database data (between PostgreSQL and OS cache). Planner is more willing to use index scans and memory-intensive plans, instead of sequential scans, if it believes data will be cached.

effective_cache_size = 80GB

# Amount of memory dedicated to storing database pages in RAM. When PostgreSQL reads or writes data, it first goes through this buffer, reducing disk access and speeding up queries. Larger shared_buffers give PostgreSQL more room to keep commonly accessed tables and indexes in memory, which reduces disk I/O and improves performance.Best practice is to set shared_buffers to about 25–40% of total server RAM. For large systems, increasing it can help, but too large a value can starve the operating system’s own cache, hurting performance.

shared_buffers = 32GB

# /etc/sysctl.conf
# 32GB / 2MB = 16384
# vm.nr_hugepages = 16384
# sysctl -p
# echo 16384 > /proc/sys/vm/nr_hugepages
# cat /proc/sys/vm/nr_hugepages
# cat /proc/meminfo | grep -i huge

huge_pages = on

# query plans accuracy

default_statistics_target = 100

# sort | hash | ...

work_mem = 4MB

# vacuum | create index | ...

maintenance_work_mem = 2GB

# Checkpoint & WAL

checkpoint_completion_target = 0.9
max_wal_size = 8GB
min_wal_size = 2GB
wal_buffers = 16MB
commit_delay = 0

# recovery_target_timeline = 'latest' # or current
# primary_conninfo = 'host=localhost port=5432 user=postgres password=... replication=true'
# primary_slot_name = 'backup'

