# ~/.config/sway/config
set $mod Mod4
xwayland disable

# output eDP-1 scale 1

input type:touchpad {
    natural_scroll enabled
    # scroll_factor 1
}

bindsym $mod+Return exec ghostty
bindsym $mod+Shift+q exec swaymsg exit
bindsym XF86AudioRaiseVolume exec wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym XF86AudioMicMute exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous
bindsym --locked XF86MonBrightnessUp exec brightnessctl set 10%+
bindsym --locked XF86MonBrightnessDown exec brightnessctl set 10%-
bindsym XF86Launch4 exec swaylock -f -c 000000
bindsym XF86TouchpadToggle exec swaymsg input "type:touchpad" events toggle

exec_always swayidle -w \
    timeout 120 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    before-sleep 'swaylock -f -c 000000'

bar {
    position top
    # position bottom
    # status_command while true; do date "+%Y-%m-%d %H:%M:%S"; sleep 1; done
    status_command ~/.config/sway/bar.sh
    colors {
        background #1d1f21
        statusline #c5c8c6
        separator  #666666
    }
    # height 28
    # font pango:monospace 10
}

# swaymsg output eDP-1 mode 2560x1440@240Hz
# swaymsg -t get_inputs
# swaymsg reload

# xdg-mime default <YOURBROWSER>.desktop x-scheme-handler/http
# xdg-mime default <YOURBROWSER>.desktop x-scheme-handler/https

# swaymsg input "ELAN1200:00 04F3:304B Touchpad" events disabled
# swaymsg input "type:touchpad" events disabled

