# apt install wireguard
# brew install wireguard-tools
# curl ifconfig.me
# wg genkey > privatekey
# cat privatekey | wg pubkey > publickey
# wg-quick up wg0
# systemctl enable wg-quick@wg0
# /etc/wireguard/wg0.conf
# /usr/local/etc/wireguard/wg0.conf

###############################################################################
# Server (UDP 51820)                                                          #
###############################################################################

[Interface]
PrivateKey = <SERVER_PRIVATE_KEY>
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
PublicKey = <CLIENT_PUBLIC_KEY>
AllowedIPs = 10.0.0.2/32

###############################################################################
# Client                                                                      #
###############################################################################

[Interface]
PrivateKey = <CLIENT_PRIVATE_KEY>
Address = 10.0.0.2/24
DNS = 1.1.1.1
# DNS = 1.0.0.1 
# DNS = 2606:4700:4700::1001

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
Endpoint = ...:51820
AllowedIPs = 10.0.0.0/24
# AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25

