# /usr/local/etc/wireguard/client.conf
# brew install wireguard-tools
# wg-quick up client
# curl ifconfig.me
# wg genkey > privatekey
# cat privatekey | wg pubkey > publickey

[Interface]
PrivateKey = ...
Address = 10.0.0.2/24
DNS = 1.1.1.1
# DNS = 1.0.0.1 # 2606:4700:4700::1001

[Peer]
PublicKey = ...
Endpoint = ...:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25

