" ~/.config/vim/vimrc
set nocompatible
set hidden
set laststatus=0
set showtabline=0
set ttimeoutlen=0
set mouse=a
set noshowmode
set incsearch
set hlsearch
set encoding=utf-8
set clipboard=unnamed
set backspace=indent,eol,start
set list
set listchars=trail:·,tab:»·,extends:›,precedes:‹,nbsp:␣
set packpath^=~/.local/share/vim
set viminfofile=~/.cache/vim/info
set completeopt+=popup
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:loaded_netrwPlugin=1
filetype plugin on
colorscheme codedark
syntax on

function! FzfQuickfixFilter()
  let l:qf_list = getqflist()
  if empty(l:qf_list)
    echo "Quickfix list is empty!"
    return
  endif

  let l:lines = []
  for item in l:qf_list
    if item.valid
      let l:bufname = bufname(item.bufnr)
      call add(l:lines, l:bufname . ':' . item.lnum . ':' . item.text)
    endif
  endfor

  let l:selection = system('fzf --ansi', join(l:lines, "\n"))

  if v:shell_error == 0 && !empty(l:selection)
    let l:parts = split(l:selection, ':')
    execute 'edit ' . l:parts[0]
    execute l:parts[1]
  endif
  redraw!
endfunction

if executable('fzf')
  command! Cfilter call FzfQuickfixFilter()
endif

if executable('rg')
  set grepprg=rg\ --vimgrep\ --smart-case
  set grepformat=%f:%l:%c:%m
endif

nnoremap <leader>g :silent grep! 
vnoremap <leader>g "jy:execute "silent grep! " . shellescape(@j)<CR>
nnoremap <C-j> :cnext<CR>
nnoremap <C-k> :cprev<CR>

function! OpenQuickfix()
  if !empty(getqflist())
    copen
    redraw!
  else
    redraw | echo "No matches found"
  endif
endfunction

augroup OpenGrepResults
  autocmd!
  autocmd QuickFixCmdPost *grep* call OpenQuickfix()
augroup END


" set autochdir
" set tags=./tags;
" let g:fzf_layout={'window': 'enew'}

