" ~/.config/vim/vimrc
set nocompatible
set hidden
set laststatus=0
set showtabline=0
set ttimeoutlen=0
set mouse=a
set noshowmode
set incsearch
set hlsearch
set encoding=utf-8
set clipboard=unnamed
set backspace=indent,eol,start
set autochdir
set list
set listchars=trail:·,tab:»·,extends:›,precedes:‹,nbsp:␣
set packpath^=~/.local/share/vim
let g:fzf_layout={'window': 'enew'}
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:loaded_netrwPlugin=1
filetype plugin on
colorscheme codedark
syntax on

