# amtool check-config alertmanager.yml

route:
  group_by: ['alertname','job']
  group_wait: 0s
  group_interval: 15s
  repeat_interval: 1h
  receiver: 'gert'
  routes:
  - receiver: 'gert'
    matchers:
    - alertname = "node:network"
    mute_time_intervals:
    - restic

receivers:
- name: 'gert'
  email_configs:
  - smarthost: 'smtp.tem.scaleway.com:587'
    from: '...'
    to: '...'
    auth_username: '...'
    auth_password: '...'
    send_resolved: true
  discord_configs:
  - webhook_url: 'https://discord.com/api/webhooks/...'
    send_resolved: true
  webhook_configs:
  - url: http://127.0.0.1:8006/debug
    send_resolved: true

inhibit_rules:
- source_matchers: [severity="critical"]
  target_matchers: [severity="warning"]
  equal: ['alertname','job']

time_intervals:
- name: restic
  time_intervals:
  - location: 'Europe/Brussels'
    times:
    - start_time: '02:00'
      end_time: '03:00'

