# promtool check config prometheus.yml
# curl -X POST http://127.0.0.1:9090/-/reload

global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - scheme: https
    basic_auth:
      username: "admin"
      password: "..."
    static_configs:
    - targets: ["alerts..."]
      labels:
        group: "..."

rule_files:
- "prometheus.rules.yml"

scrape_configs:
- job_name: "prometheus"
  scheme: https
  metrics_path: "/metrics"
  basic_auth:
    username: "admin"
    password: "..."
  static_configs:
  - targets: ["prometheus...", "alerts..."]
    labels:
      group: "..."

- job_name: "node"
  scheme: https
  metrics_path: "/metrics-node"
  basic_auth:
    username: "admin"
    password: "..."
  static_configs:
  - targets: ["..."]
    labels:
      group: "..."

- job_name: "nginx"
  scheme: https
  metrics_path: "/metrics-nginx"
  basic_auth:
    username: "..."
    password: "..."
  static_configs:
  - targets: ["..."]
    labels:
      group: "..."

- job_name: "postgres"
  scheme: https
  metrics_path: "/metrics-postgres"
  basic_auth:
    username: "admin"
    password: "..."
  static_configs:
  - targets: ["..."]
    labels:
      group: "..."

- job_name: "jaeger"
  scheme: http
  metrics_path: "/metrics"
  static_configs:
  - targets: ["127.0.0.1:8888", "127.0.0.1:8890"]
    labels:
      group: "..."

  # metric_relabel_configs:
  # - source_labels: [__name__]
  #   regex: "(prometheus_http_request_duration_seconds_bucket|prometheus_http_response_size_bytes_bucket)"
  #   action: drop

