server {
    server_name _;

    limit_conn conn 100;
    limit_conn_status 429;

    limit_req zone=req burst=30 nodelay;
    limit_req_status 429;

    location = /metrics {
        stub_status on;
        allow 127.0.0.1;
        deny all;
    }

    location /.well-known {
        root /var/lib/letsencrypt;
    }

    location / {
        # root /usr/share/nginx/html;
        return 301 https://$host$request_uri;
    }

    listen 80 default_server;
    listen [::]:80 default_server;
}
