server {
    server_name _;

    limit_conn conn 100;
    limit_conn_status 429;

    limit_req zone=req burst=30 nodelay;
    limit_req_status 429;

    location /.well-known {
        root /var/lib/letsencrypt;
    }

    location /metrics {
        stub_status on;
        allow 127.0.0.1;
        deny all;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

#    location / {
#        return 301 https://$host$request_uri;
#    }

    listen 80 default_server;
    listen [::]:80 default_server;
}

# server {
#     listen 443 ssl default_server;
#     listen [::]:443 ssl default_server;
#     server_name _;
#     ssl_certificate /etc/letsencrypt/live/default/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/default/privkey.pem;
#
#     location /metrics {
#         auth_basic "Metrics Node";
#         auth_basic_user_file /etc/nginx/htpasswd;
#         proxy_redirect off;
#         proxy_pass http://127.0.0.1:9100/metrics;
#     }
#
#     root /var/www/html;
#     autoindex on;
# }

#     error_page  404              /404.html;
#     error_page  500 502 503 504  /50x.html;
#
#     location = /50x.html {
#         root   /usr/share/nginx/html;
#     }

