server {
    server_name _;

    limit_conn conn 100;
    limit_conn_status 429;

    limit_req zone=req burst=30 nodelay;
    limit_req_status 429;

    add_header Alt-Svc 'h3=":443"; ma=86400';
    proxy_redirect off;

    location = /metrics-node {
        auth_basic "Metrics Node";
        auth_basic_user_file /etc/nginx/htpasswd;
        proxy_pass http://127.0.0.1:9100/metrics;
    }

    location = /metrics-nginx {
        auth_basic "Metrics Nginx";
        auth_basic_user_file /etc/nginx/htpasswd;
        proxy_pass http://127.0.0.1:9113/metrics;
    }

    location = /metrics-postgres {
        auth_basic "Metrics Postgres";
        auth_basic_user_file /etc/nginx/htpasswd;
        proxy_pass http://127.0.0.1:9187/metrics;
    }

    location / {
        # root /usr/share/nginx/html;
        root /var/lib/nginx;
        autoindex on;
    }

    listen 443 ssl default_server;
    listen 443 quic reuseport default_server;

    listen [::]:443 ssl default_server;
    listen [::]:443 quic reuseport default_server;

    ssl_certificate /etc/letsencrypt/live/default/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/default/privkey.pem;
}
