server {
    server_name ...;

    limit_conn conn 100;
    limit_conn_status 429;

    limit_req zone=req burst=30 nodelay;
    limit_req_status 429;

    add_header Alt-Svc 'h3=":443"; ma=86400';

    location /metrics {
        auth_basic "Metrics";
        auth_basic_user_file /etc/nginx/htpasswd;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:9100/metrics;
    }

    listen 443 ssl;
    listen 443 quic reuseport;

    listen [::]:443 ssl;
    listen [::]:443 quic reuseport;

    ssl_certificate /etc/letsencrypt/live/default/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/default/privkey.pem;
}
