server {
    server_name gert.ovh;

    limit_conn conn 100;
    # limit_conn_status 429;
    limit_req zone=req burst=30 nodelay;
    # limit_req_status 429;

    client_max_body_size 4m;
    add_header Alt-Svc 'h3=":443"; ma=86400';

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;

    location / {
        proxy_pass http://127.0.0.1:8069;
    }

    location ~* ^/[^/]+/static/.+$ {
        proxy_pass http://127.0.0.1:8069;
        proxy_set_header Host $host;
        proxy_set_header Authorization "";
        proxy_set_header Cookie "";
        proxy_cache filestore;
        proxy_cache_valid 200 302 60m;
        proxy_cache_valid 404 1m;
        proxy_cache_bypass $http_cache_control;
        proxy_ignore_headers Cache-Control Expires Set-Cookie;
        proxy_hide_header Set-Cookie;
        add_header Alt-Svc 'h3=":443"; ma=86400';
        add_header X-Cache-Status $upstream_cache_status;
        expires 60m;
    }

    location /websocket {
        proxy_pass http://127.0.0.1:8072;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    listen 443 ssl;
    listen 443 quic;

    listen [::]:443 ssl;
    listen [::]:443 quic;

    ssl_certificate /etc/letsencrypt/live/default/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/default/privkey.pem;
}

    # location / {
    #     proxy_pass http://127.0.0.1:8000;

    #     add_header Access-Control-Allow-Origin "*" always;
    #     add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
    #     add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

    #     if ($request_method = OPTIONS) {
    #         return 204;
    #     }

    # }

#     error_page  404              /404.html;
#     error_page  500 502 503 504  /50x.html;
#
#     location = /50x.html {
#         root   /usr/share/nginx/html;
#     }

