server {
    listen 443 ssl;
    server_name dev.clubit.cloud;
    ssl_certificate /etc/letsencrypt/live/default/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/default/privkey.pem;

    # proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    client_max_body_size 4m;

    location / {
        proxy_pass http://127.0.0.1:8169;
    }

    location ~ ^/[^/]+/static/.+$ {
        proxy_pass http://127.0.0.1:8169;
        proxy_cache_valid 200 60m;
        expires 60m;
    }

    location /websocket {
        proxy_pass http://127.0.0.1:8172;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

}

