CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    display_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE credentials (
    credential_id TEXT PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    public_key JSONB NOT NULL,
    sign_count INTEGER NOT NULL DEFAULT 0,
    transports TEXT[],
    aaguid UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_used_at TIMESTAMPTZ
);

CREATE INDEX ix_credentials_user_id ON credentials(user_id);

-- Credential id generated by the authenticator (Base64URL encoded)
-- The public key (COSE format, typically stored as JSONB for flexibility)
-- Sign count to detect cloned authenticators (MUST be updated on every login)
-- Transports helps UI identify the key (e.g., "YubiKey", "iPhone TouchID")
-- array of ['usb', 'nfc', 'ble', 'internal']
-- AAGUID for authenticator identification

