CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    display_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE credentials (
    -- Unique ID generated by the authenticator (Base64URL encoded)
    credential_id TEXT PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    -- The public key (COSE format, typically stored as JSONB for flexibility)
    public_key JSONB NOT NULL,
    -- Used to detect cloned authenticators (MUST be updated on every login)
    sign_count INTEGER NOT NULL DEFAULT 0,
    -- Helps UI identify the key (e.g., "YubiKey", "iPhone TouchID")
    transports TEXT[], -- array of ['usb', 'nfc', 'ble', 'internal']
    -- Optional: Stores the AAGUID for authenticator identification
    aaguid UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_used_at TIMESTAMPTZ
);

CREATE INDEX idx_credentials_user_id ON credentials(user_id);

