# /etc/sysctl.d/99-local.conf

# 17626 * 2MB
# cat /proc/meminfo | grep -i huge
# cat /proc/sys/vm/nr_hugepages
# echo 17626 > /proc/sys/vm/nr_hugepages

vm.nr_hugepages = 17626

###############################################################################

# sysctl -w net.ipv4.ip_forward=1
# cat /proc/sys/net/ipv4/ip_forward
net.ipv4.ip_forward = 1
# net.ipv4.tcp_syncookies

###############################################################################

# sysctl -w net.ipv6.conf.all.forwarding=1
# cat /proc/sys/net/ipv6/conf/all/forwarding
net.ipv6.conf.all.forwarding = 1

###############################################################################

# Generate privacy ipv6
net.ipv6.conf.all.use_tempaddr = 0
net.ipv6.conf.default.use_tempaddr = 0

# Accept Router Advertisements
net.ipv6.conf.all.accept_ra=2
net.ipv6.conf.default.accept_ra=2

# net.ipv6.conf.eth0.accept_ra = 2
# net.ipv6.conf.eth0.autoconf = 1

# sysctl -p /etc/sysctl.conf
# sysctl --system

###############################################################################

# ip -6 route show
# ip -6 route show default
# ip -6 route get 2001:4860:4860::8888
# ip -6 route add default via fe80::... dev eth0
# ip -6 addr add 2001:.../64 dev eth0
# ip -6 addr show dev eth0
# ip -6 addr flush dev eth0
# ip -6 link set dev eth0 up
# ip -6 neighbor show
# ip -6 neighbor show dev eth0

# ping6 -c 4 2001:4860:4860::8888

# :: -> 0.0.0.0
# ::1 -> 127.0.0.1
# [::]:80 -> 0.0.0.0:80
# fe80:: -> link
# ff:fe -> mac

