# /etc/sysctl.d/99-local.conf

# 17626 * 2MB
# cat /proc/meminfo | grep -i huge
# cat /proc/sys/vm/nr_hugepages
# echo 17626 > /proc/sys/vm/nr_hugepages

vm.nr_hugepages = 17626

# sysctl -w net.ipv4.ip_forward=1
# sysctl -w net.ipv6.conf.all.forwarding=1
# cat /proc/sys/net/ipv4/ip_forward
# cat /proc/sys/net/ipv6/conf/all/forwarding

net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1

# sysctl net.ipv4.tcp_syncookies
# cat /proc/sys/net/ipv4/tcp_syncookies
# sysctl --system

